apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: declarations-api
  namespace: apps
  labels:
    app: declarations-api
spec:
  # This is needed for the nginx-ingress helm chart
  ingressClassName: nginx
  rules:
  - host: declarations-api.carlson.fam
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: declarations-api
            port:
              number: 8080
